### PR TITLE
The core of the game

### PR DESCRIPTION
**Pull request by FayeAlephNil**
Adds a core to the game. The core currently consists of a lib and a main.rb. The main.rb is where all the top-level code will go. Currently there is an example of how to use the core there.

The core currently has these features
- Crafting
- Elements
- Production
- Saving/Loading

### CODE REVIEW

**Comment by elifoster** [comment]
Someone that actually knows and understands Ruby, as well as the Ruby Style Guide should review this. @trajing @chbachman ?

**Comment by chbachman** [comment]
Never used Ruby.

**Comment by FayeAlephNil** [comment]
Yeah @chbachman doesn't know that :laughing: @trajing will be reviewing this at some point

**Comment by FayeAlephNil** [comment]
Did a ton of commenting. Probably going to watch some anime then go to sleep now

**Comment by trajing** [comment]
Looking through, I can see that lib/managers/sub.rb has parts indented by four spaces, and parts indented by two. Let's stick with one indentation, and I'm pretty sure the style guide calls for two spaces. I'll check and let you know if it's four spaces.

**Comment by FayeAlephNil** [comment]
@trajing yeah I always seem to get that problem because I instinctively press tab...

**Comment by trajing** [comment]
Ignore last comment, I'm an idiot

**Comment by FayeAlephNil** [comment]
@trajing is crazy. It wasn't four

**Comment by trajing** [comment]
Code follows the style guide and is properly documented, merging..

**Comment by FayeAlephNil** [comment]
Deleted the branch as we don't need it anymore

**Pull request merged**
